[project]
name = "video-encoder"
version = "0.1.0"
description = ""
authors = [
    {name = "Mihail Komarov",email = "michaelkomarov03@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "pydantic (==2.12.5)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
